spring:
  datasource:
    username: root
#    password: password
#    url: jdbc:mysql://35.186.151.166:3306/canal_target
    password: oh_my_ody!
    url: jdbc:mysql://127.0.0.1:13306/canal_target
    driver-class-name: com.mysql.cj.jdbc.Driver