canal:
  hostname: canal-server-1
  port: 11111
  destination: user
  username:
  password:
  subscribe: source..*
  target:
    suffix: _canal

spring:
  datasource:
    username: awsuser111
    password: Awsuser111Awsuser111Awsuser111
    jdbc-url: jdbc:redshift://redshift-cluster-1.ci817qdxya13.ap-southeast-1.redshift.amazonaws.com:5439/dev
    driver-class-name: com.amazon.redshift.jdbc.Driver