canal:
  hostname: 35.186.151.166
  port: 21111
  destination: canal-source
  username:
  password:
  subscribe: canal_source..*

spring:
  datasource:
    username: root
    password: oh_my_ody!
    jdbc-url: jdbc:mysql://127.0.0.1:13306/canal_target
    driver-class-name: com.mysql.cj.jdbc.Driver